### ISSUE TITLE
session not created

### ISSUE THREAD

**Issue by stickerx** [stavros-melidoniotis/egs_automation#2]
DevTools listening on ws://127.0.0.1:58740/devtools/browser/67c9dca7-51ca-44fc-b4d4-67bb1b6104e9
Traceback (most recent call last):
  File "C:\Users\stickerx\Desktop\egs_automation-master\main.py", line 50, in <module>
    browser = create_browser_driver(platform.system())
  File "C:\Users\stickerx\Desktop\egs_automation-master\main.py", line 40, in create_browser_driver
    browser_driver = webdriver.Chrome(executable_path=windows_path + '\chromedriver.exe')
  File "C:\Users\stickerx\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\stickerx\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\stickerx\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\stickerx\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\stickerx\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

**Comment by stavros-melidoniotis** [comment]
Hey @stickerx , sorry for the late response. You should find out which version of Chrome you're currently using by typing [chrome://version/](chrome://version/) in your address bar. Then download the corresponding chromedriver from [https://chromedriver.chromium.org/downloads](https://chromedriver.chromium.org/downloads). 

Please note that you should repeat this process each time Chrome performs an update.

**Comment by stickerx** [comment]
![2021-03-11_165243](https://user-images.githubusercontent.com/41187653/110823831-61a17100-828a-11eb-9282-85bda7e35eb9.jpg)

 
I do that, but I got another error ;(
 I am not good at automation, sorry.

**Comment by stavros-melidoniotis** [comment]
This seems to be an error with the code itself and not your setup. Most likely EGS webpage has changed since the last time I updated this repo and that's why you're getting the `Message: no such element: Unable to locate element` error. 

You can freely edit the code yourself if that's something you want to do.
